# config/routes.yaml

nelmio_api_doc:
    path: /api/docs
    controller: nelmio_api_doc.controller.swagger_ui

controllers:
    resource: '../src/Controller/'
    type: attribute
metrics:
  path: /metrics
  controller: Symfony\Bundle\FrameworkBundle\Controller\MetricsController

reset_password:
  path: /api/reset-password
  controller: App\\Controller\\ResetPasswordController
  methods: [POST]
